### ISSUE TITLE
Custom Configuration

### ISSUE THREAD

**Issue by wavyx** [mathpere/grails-hibernate-search-plugin#15]
Hi,

I was wondering if there is specific configuration keys to tweak the Lucene IndexWriter or change the Hibernate Search settings.

For eg, I would like to increase for WRITE_LOCK_TIMEOUT (https://lucene.apache.org/core/old_versioned_docs/versions/3_1_0/api/all/org/apache/lucene/index/IndexWriterConfig.html#WRITE_LOCK_TIMEOUT) or set the indexing strategy (hibernate.search.indexing_strategy) to manual.

Is there a full list of config keys supported by hibernate-search plugin. So far I have:
- search.default.directory_provider = 'filesystem'
- search.default.indexBase = '/path/to/your/indexes'
- search.default.indexBaseJndiName = 'java:comp/env/luceneIndexBase'

Thanks for your help

**Comment by lgrignon** [comment]
It seems that write lock timeout have been deprecated after all :) but things have changed, you can now configure Hibernate Search through standard configuration:
https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#lucene-indexing-performance
For instance, in your Grails 3 application.yml:
```
hibernate:
    cache:
        use_second_level_cache: true
        use_query_cache: true
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    search:
        default:
            indexmanager: near-real-time
            directory_provider: filesystem
            indexwriter:
                infostream: true
```
